---
title: "Nov 2024 - Wisconsin Election Results"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, echo = F)
library(dplyr)
library(tidyr)
library(sf)
library(leaflet)
library(gt)

rep.unit.tables <- readRDS(here::here("2024-nov/analysis/rep-unit-html-tables.rds"))
df <- sf::st_read(here::here("2024-nov/analysis/election-results-2012-2024.geojson")) |>
  # add two-party totals
  mutate(USSTOT24 = USSDEM24 + USSREP24,
         USSTOT22 = USSDEM22 + USSREP22,
         USSTOT16 = USSDEM16 + USSREP16,
         USSTOT18 = USSDEM18 + USSREP18,
         PRETOT24 = PREDEM24 + PREREP24,
         PRETOT20 = PREDEM20 + PREREP20,
         PRETOT16 = PREDEM16 + PREREP16) |>
  # compute margins
  mutate(PREMARG24 = (PREDEM24/PRETOT24 - PREREP24/PRETOT24)*100,
         PREMARG20 = (PREDEM20/PRETOT20 - PREREP20/PRETOT20)*100,
         PREMARG16 = (PREDEM16/PRETOT16 - PREREP16/PRETOT16)*100,
         USSMARG18 = (USSDEM18/USSTOT18 - USSREP18/USSTOT18)*100,
         USSMARG22 = (USSDEM22/USSTOT22 - USSREP22/USSTOT22)*100,
         USSMARG24 = (USSDEM24/USSTOT24 - USSREP24/USSTOT24)*100,
         PREMARGshift = PREMARG24 - PREMARG20) |>
  mutate(table = as.character(rep.unit.tables),
         label = paste(county, "COUNTY -", reporting_unit, "<br>",
                       table))

```


```{r}
#| column: body-outset
#| fig-height: 8

margin.palette <- colorBin("RdBu", domain = orig.votes$PREMARG24,
                           bins = c(-Inf, -25, -15, -5, 5, 15, 25, Inf))
shift.palette <- colorBin("RdBu", domain = orig.votes$PREMARGshift,
                          bins = c(-Inf, -10, -6, -2, 2, 6, 10, Inf))

df |>
  leaflet() |>
  addMapPane("background_map", zIndex = 410) %>%  # Level 1: bottom
  addMapPane("polygons", zIndex = 420) %>%        # Level 2: middle
  addMapPane("labels", zIndex = 430) %>%          # Level 3: top
  addProviderTiles(provider = providers$CartoDB.PositronNoLabels,
                   options = pathOptions(pane = "background_map")) |>
  addPolygons(weight = 1, opacity = 0.25, color = "black",
              label = ~lapply(label, htmltools::HTML),
              fillColor = ~margin.palette(PREMARG24),
              fillOpacity = 0.75,
              group = "Pres margin 2024",
              options = pathOptions(pane = "polygons")) |>
  addPolygons(weight = 1, opacity = 0.25, color = "black",
              label = ~lapply(label, htmltools::HTML),
              fillColor = ~shift.palette(PREMARGshift),
              fillOpacity = 0.75,
              group = "Pres margin shift, 2020-2024",
              options = pathOptions(pane = "polygons")) |>
  addProviderTiles(provider = providers$CartoDB.PositronOnlyLabels,
                   options = pathOptions(pane = "labels")) |>
  addLegend(position = "bottomleft", pal = shift.palette, values = ~PREMARGshift,
            title = "2024 margin - 2020 margin",
            group = "Pres margin shift, 2020-2024") |>
  addLegend(position = "bottomleft", pal = margin.palette, values = ~PREMARG24,
            title = "Harris % minus Trump %", group = "Pres margin 2024") |>
  addLayersControl(baseGroups = c("Pres margin 2024", "Pres margin shift, 2020-2024"),
                   options = layersControlOptions(collapsed = F))
```
