on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '2024-nov/processed/matched-reporting-unit-results.geojson'

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2 # automatically sets up cache
        with:
          packages: |
            any::tidyr
            any::dplyr
            any::gt
            any::sf
            any::leaflet
            any::here
            any::htmltools

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: 2024-nov/qmd-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}